### ISSUE TITLE
Develop backend functionality for the List page

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#406]
### Description
We need to develop backend functionality for a user's list, this includes database read/write functions, routing GET/POST functions, as well as a function in the frontend to POST to the backend. Shouldn't be difficult, I just have to find the time

**Comment by samforstot** [comment]
Riley has set up a template for you @steeleelliott03 , pull the branch and take a look in Database.go and List.go

**Comment by rileycleavenger** [comment]
**TO-DO:** 
Create Backend Functions for the List functionality, create a table in MealDealz.db called UserLists where each entry has username (primary key), FoodItem.Name, FoodItem.Quantity, and List.TimeAdded

Using the rest of Database.go as a reference, and the List struct in List.go, complete the following 3 functions:

- [ ] `func (d *Database) ReadList(currUser User) List`
- [ ] `func (d *Database) WriteList(newItem FoodItem, currUser User)`
- [ ] `func (d *Database) UpdateListItem(newItem FoodItem, currUser User)`

Everything is in [this branch ](https://github.com/TylerMetz/Saucier720/tree/WIP-406-ListBackend)
